# Generated by Django 3.2.9 on 2021-11-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
