# Generated by Django 3.2.9 on 2021-11-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20211116_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='picture.jpg', null=True, upload_to='banner/')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(blank=True, default='picture.jpg', null=True, upload_to='samples/')),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='brands',
            field=models.ImageField(blank=True, default='picture.jpg', null=True, upload_to='brand/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='picture.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='picture.jpg', null=True, upload_to='images/'),
        ),
    ]
