# Generated by Django 3.2.9 on 2021-11-16 16:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20211116_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('heading', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, default='picture.jpg', upload_to='training/')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer',
        ),
        migrations.AlterField(
            model_name='sample',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
