# Generated by Django 3.2.9 on 2021-11-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211116_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='price',
            field=models.FloatField(blank=True, default=5000, null=True),
        ),
    ]
