# Generated by Django 3.2.9 on 2021-11-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_training_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='about_img',
            field=models.ImageField(blank=True, default='picture.jpg', null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='cart_icon',
            field=models.ImageField(blank=True, default='picture.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='icon',
            field=models.ImageField(blank=True, default='picture.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.ImageField(blank=True, default='picture.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='menu_icon',
            field=models.ImageField(blank=True, default='picture.jpg', null=True, upload_to='images/'),
        ),
    ]
