# Generated by Django 3.2.9 on 2021-11-25 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_checkout_shopcart_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('pay_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.userprofile')),
            ],
            options={
                'verbose_name': 'TrainingReg',
                'verbose_name_plural': 'TrainingReg',
                'db_table': 'TrainingReg',
                'managed': True,
            },
        ),
    ]
