# Generated by Django 3.2.9 on 2021-11-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20211126_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingreg',
            name='payment_code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
