# Generated by Django 3.2.9 on 2021-11-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_trainingreg_payment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingreg',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
