# Generated by Django 3.2.9 on 2021-11-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_trainingreg_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingreg',
            name='address',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='trainingreg',
            name='city',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='trainingreg',
            name='country',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='trainingreg',
            name='state',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
