# Generated by Django 3.2.9 on 2021-11-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20211128_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingreg',
            name='fee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
