# Generated by Django 3.2.9 on 2021-11-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20211130_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingreg',
            name='ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingreg',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trainingreg',
            name='end_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trainingreg',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
