# Generated by Django 3.2.9 on 2021-11-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20211130_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingreg',
            name='start_date',
            field=models.DateField(),
        ),
    ]
