# Generated by Django 3.2.9 on 2021-11-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_trainingreg_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingreg',
            name='start_date',
            field=models.DateField(),
        ),
    ]
