# Generated by Django 3.2.9 on 2021-11-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_trainingreg_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingreg',
            name='fee',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='trainingreg',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
