# Generated by Django 3.2.9 on 2021-11-30 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20211130_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingreg',
            name='address',
        ),
        migrations.RemoveField(
            model_name='trainingreg',
            name='city',
        ),
        migrations.RemoveField(
            model_name='trainingreg',
            name='country',
        ),
        migrations.RemoveField(
            model_name='trainingreg',
            name='state',
        ),
    ]
