# Generated by Django 3.2.9 on 2021-12-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20211130_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
